import type { ComponentType, CSSProperties } from "react";
import {
  PiArrowsClockwiseDuotone,
  PiBellDuotone,
  PiBookOpenTextDuotone,
  PiBriefcaseDuotone,
  PiCalendarDuotone,
  PiChatCircleDuotone,
  PiCheckCircleDuotone,
  PiClockDuotone,
  PiCursorClickDuotone,
  PiDesktopDuotone,
  PiDeviceMobileDuotone,
  PiEnvelopeSimpleDuotone,
  PiEyeDuotone,
  PiFolderDuotone,
  PiHandTapDuotone,
  PiLightningDuotone,
  PiListChecksDuotone,
  PiLockKeyDuotone,
  PiPencilSimpleLineDuotone,
  PiPhoneDuotone,
  PiPlugsConnectedDuotone,
  PiQuestionDuotone,
  PiScrollDuotone,
  PiShieldCheckDuotone,
  PiTrashDuotone,
  PiUserCircleDuotone,
  PiUsersThreeDuotone,
} from "react-icons/pi";
import type { IconName } from "@/content/types";

type Icon = ComponentType<{ size?: number; style?: CSSProperties; className?: string }>;

export const ICONS: Record<IconName, Icon> = {
  search: PiScrollDuotone,
  draft: PiPencilSimpleLineDuotone,
  calendar: PiCalendarDuotone,
  tasks: PiListChecksDuotone,
  plug: PiPlugsConnectedDuotone,
  cursor: PiCursorClickDuotone,
  check: PiCheckCircleDuotone,
  lock: PiLockKeyDuotone,
  hand: PiHandTapDuotone,
  user: PiUserCircleDuotone,
  trash: PiTrashDuotone,
  phone: PiPhoneDuotone,
  mobile: PiDeviceMobileDuotone,
  desktop: PiDesktopDuotone,
  clock: PiClockDuotone,
  list: PiListChecksDuotone,
  envelope: PiEnvelopeSimpleDuotone,
  chat: PiChatCircleDuotone,
  shield: PiShieldCheckDuotone,
  folder: PiFolderDuotone,
  bell: PiBellDuotone,
  arrows: PiArrowsClockwiseDuotone,
  users: PiUsersThreeDuotone,
  briefcase: PiBriefcaseDuotone,
  book: PiBookOpenTextDuotone,
  lightning: PiLightningDuotone,
  eye: PiEyeDuotone,
  question: PiQuestionDuotone,
};
