// Every URL planned for the content build-out, so pages can cross-link before
// the target exists. Only used when CONTENT_ALLOW_PLANNED=1 (scripts/check-content.ts).
// `next build` always validates against real pages only.

export const PLANNED: Record<string, string[]> = {
  product: ["/how-it-works", "/ios", "/android"],
  feature: [
    "/features",
    "/features/decide",
    "/features/tasks",
    "/features/inboxes",
    "/features/search",
    "/features/drafting",
    "/features/scheduling",
    "/features/follow-ups",
    "/features/documents",
  ],
  integration: [
    "/integrations",
    "/integrations/gmail",
    "/integrations/outlook",
    "/integrations/slack",
    "/integrations/microsoft-teams",
    "/integrations/whatsapp-business",
    "/integrations/instagram-business",
    "/integrations/messenger",
    "/integrations/sms",
    "/integrations/groupme",
    "/integrations/google-drive",
    "/integrations/onedrive",
    "/integrations/google-calendar",
    "/integrations/imessage",
    "/integrations/dropbox",
    "/integrations/notion",
    "/integrations/github",
  ],
  "use-case": [
    "/for",
    "/for/founders",
    "/for/executive-assistants",
    "/for/sales",
    "/for/recruiters",
    "/for/consultants",
    "/for/agencies",
    "/for/real-estate-agents",
    "/for/small-business-owners",
  ],
  compare: [
    "/compare",
    "/compare/synced-vs-superhuman",
    "/compare/synced-vs-shortwave",
    "/compare/synced-vs-fyxer",
    "/compare/synced-vs-gemini-in-gmail",
    "/compare/synced-vs-copilot-in-outlook",
    "/compare/synced-vs-sanebox",
    "/compare/synced-vs-chatgpt",
    "/compare/synced-vs-spark",
    "/alternatives/superhuman-alternatives",
    "/alternatives/sanebox-alternatives",
    "/alternatives/fyxer-alternatives",
    "/best-ai-email-assistants",
  ],
  glossary: [
    "/glossary",
    "/glossary/action-plan",
    "/glossary/decide-queue",
    "/glossary/inbox-connector",
    "/glossary/output-integration",
    "/glossary/human-in-the-loop-approval",
    "/glossary/ai-inbox-assistant",
    "/glossary/agentic-email",
    "/glossary/email-triage",
    "/glossary/inbox-zero",
    "/glossary/email-summarization",
    "/glossary/smart-reply",
    "/glossary/follow-up-tracking",
    "/glossary/email-to-task",
    "/glossary/natural-language-search",
    "/glossary/unified-inbox",
    "/glossary/email-delegation",
    "/glossary/google-limited-use-policy",
    "/glossary/oauth-scopes",
    "/glossary/encryption-at-rest",
    "/glossary/retrieval-augmented-generation",
    "/glossary/large-language-model",
    "/glossary/ai-agent",
    "/glossary/prompt-injection",
    "/glossary/scheduled-send",
    "/glossary/undo-send",
    "/glossary/shared-inbox",
    "/glossary/email-thread",
    "/glossary/calendar-coordination",
  ],
  guide: [
    "/guides",
    "/guides/how-to-automate-email-follow-ups",
    "/guides/how-to-get-to-inbox-zero",
    "/guides/how-to-summarize-long-email-threads",
    "/guides/how-to-schedule-meetings-over-email",
    "/guides/how-to-turn-emails-into-tasks",
    "/guides/how-to-search-email-and-files-together",
    "/guides/how-to-use-ai-to-draft-email-replies",
    "/guides/how-to-delegate-email",
    "/guides/how-to-manage-multiple-email-accounts",
    "/guides/how-to-stop-missing-slack-messages",
    "/guides/gmail-oauth-scopes-explained",
    "/guides/is-it-safe-to-give-ai-access-to-your-email",
    "/guides/how-to-evaluate-an-ai-email-assistant",
    "/guides/how-to-manage-whatsapp-business-messages",
    "/guides/how-to-manage-instagram-business-dms",
    "/guides/how-to-catch-up-on-email-after-vacation",
    "/guides/how-to-batch-process-email",
    "/guides/how-to-organize-gmail-with-labels-and-filters",
    "/guides/how-to-set-up-rules-in-outlook",
    "/guides/how-to-reply-to-emails-faster",
    "/guides/how-to-find-an-old-email-attachment",
  ],
  template: [
    "/templates",
    "/templates/follow-up-after-no-response",
    "/templates/follow-up-after-meeting",
    "/templates/meeting-request",
    "/templates/reschedule-meeting",
    "/templates/decline-meeting-invitation",
    "/templates/polite-decline",
    "/templates/introduction-email",
    "/templates/out-of-office-message",
    "/templates/delegation-email",
    "/templates/project-status-update",
    "/templates/payment-reminder",
    "/templates/thank-you-after-interview",
    "/templates/project-kickoff-email",
    "/templates/apology-for-late-reply",
    "/templates/sharing-your-availability",
    "/templates/deadline-extension-request",
  ],
  help: [
    "/help",
    "/help/sign-in-with-your-phone-number",
    "/help/didnt-get-a-verification-code",
    "/help/connect-an-inbox",
    "/help/connect-an-output-integration",
    "/help/disconnect-an-integration",
    "/help/revoke-google-access",
    "/help/approve-or-edit-a-draft",
    "/help/undo-a-sent-message",
    "/help/schedule-a-message",
    "/help/delegate-a-task",
    "/help/weekly-limit-reached",
    "/help/use-synced-on-web-and-mobile",
    "/help/delete-your-account",
    "/help/supported-browsers-and-devices",
    "/help/notification-settings",
    "/help/filter-your-conversations",
    "/help/star-snooze-and-archive",
    "/help/beta-limitations",
  ],
  blog: [
    "/blog",
    "/blog/why-synced-asks-before-it-sends",
    "/blog/your-inbox-is-a-to-do-list",
    "/blog/work-happens-in-more-than-email",
  ],
  company: ["/about", "/contact", "/faq", "/press", "/changelog"],
};

export const ALL_PLANNED = Object.values(PLANNED).flat();
