import type { Page } from "../types";

export const outOfOfficeMessage: Page = {
  slug: "/templates/out-of-office-message",
  cluster: "template",
  parent: "/templates",
  title: "Out-of-Office Message Templates for Email | Synced",
  h1: "Out-of-office message",
  navLabel: "Out-of-office message",
  cardText: "Auto-replies that say when you're back and who to ask: vacation, internal, extended leave, and travel.",
  description:
    "Out-of-office message templates for vacation, a short internal auto-reply, extended leave, and travel. Each gives a return date and a backup contact.",
  eyebrow: "Email template",
  intro: "The auto-reply has one job: tell the sender what happens to their email while you're gone.",
  answer:
    "An out-of-office message should give the date you're back (a real date, not \"next week\"), say whether you'll see email before then, and name one person to contact for anything urgent, with their email address. Three or four lines is enough. If your email client allows it, set a shorter version for people inside your company.",
  primaryIntent: "out of office message template",
  published: "2026-09-13",
  updated: "2026-09-13",
  body: [
    { type: "h2", text: "Standard vacation auto-reply" },
    { type: "p", text: "Works for internal and external senders. The subject line is usually generated by your email client." },
    {
      type: "template",
      label: "Vacation",
      text: "Hi,\n\nI'm out of the office until [day, date] with limited access to email.\n\nFor anything urgent about [area], please contact [Name] at [email]. Otherwise I'll reply when I'm back.\n\nThanks,\n[Your name]",
    },
    { type: "h2", text: "Short internal out-of-office" },
    { type: "p", text: "Colleagues need less. Outlook's Automatic Replies has separate inside and outside messages; in Gmail, you can limit the vacation responder to people in your contacts or organization." },
    {
      type: "template",
      label: "Internal",
      text: "Out until [date]. [Name] is covering [project/area] while I'm away. Anything else can wait for me, and I'll catch up on [day].",
    },
    { type: "h2", text: "Extended leave out-of-office" },
    { type: "p", text: "For parental leave, medical leave, or a sabbatical. You don't owe anyone the reason. Say you won't be checking email so nobody waits." },
    {
      type: "template",
      label: "Extended leave",
      text: "Hello,\n\nI'm on leave until [date] and won't be checking email during that time.\n\nWhile I'm away:\n- For [area], contact [Name] at [email]\n- For [area], contact [Name] at [email]\n\nIf your email needs my attention after I return, please resend it after [date] so it doesn't get lost.\n\nThank you,\n[Your name]",
    },
    { type: "h2", text: "Conference or travel auto-reply" },
    { type: "p", text: "For when you're working but slow. Set expectations on reply time rather than saying you're unreachable." },
    {
      type: "template",
      label: "Travel",
      text: "Hi,\n\nI'm at [event / traveling] through [date] and replying more slowly than usual, usually within [one or two business days].\n\nIf it can't wait, [Name] ([email]) can help, or text me at [number] for anything time-sensitive.\n\n[Your name]",
    },
    { type: "h2", text: "When to turn on an auto-reply" },
    {
      type: "list",
      items: [
        "Turn it on for any full business day you won't read email, and for longer stretches of slow replies.",
        "Skip it for a half day or a single afternoon of meetings. A calendar block is enough.",
        "Tell your backup contact before you name them in the message.",
      ],
    },
    { type: "h2", text: "What to avoid" },
    {
      type: "list",
      items: [
        "\"I'll respond as soon as possible.\" Give the date instead.",
        "Your personal phone number in an external auto-reply. It goes to every newsletter and cold emailer too.",
        "Oversharing where you are. \"Out of the office\" is enough for senders you don't know.",
        "Forgetting to turn it off. Set an end date when you set it up.",
      ],
    },
    { type: "h2", text: "What Synced does while you're away" },
    {
      type: "p",
      text: "Synced doesn't set your auto-reply, so use the built-in setting in Gmail or Outlook. It helps on the other end: messages that arrive while you're out still get Action Plans (up to your plan's weekly limit), so you come back to drafted replies waiting in [Decide](/features/decide) instead of a raw pile. The guide on [catching up after vacation](/guides/how-to-catch-up-on-email-after-vacation) covers the manual method too.",
    },
  ],
  faqs: [
    {
      q: "What should an out-of-office message say?",
      a: "The date you're back, whether you're reachable before then, and who to contact for urgent issues with their email address. Anything more is optional.",
    },
    {
      q: "Should I say why I'm out of the office?",
      a: "You don't need to. \"Out of the office\" or \"on leave\" is standard. Some people mention a conference because it explains slower replies, but a reason is never required.",
    },
    {
      q: "How do I set up an out-of-office in Gmail or Outlook?",
      a: "In Gmail, open Settings, then See all settings, and turn on the vacation responder on the General tab. In Outlook, find Automatic Replies in Settings (or under File in the desktop app) and set start and end times.",
    },
  ],
  related: ["/templates/delegation-email", "/templates/apology-for-late-reply", "/guides/how-to-catch-up-on-email-after-vacation"],
};
