import type { Page } from "../types";

export const changelog: Page = {
  slug: "/changelog",
  cluster: "company",
  title: "Synced Changelog: New Features and Fixes | Synced",
  h1: "Changelog.",
  navLabel: "Changelog",
  cardText: "What changed in Synced, week by week, in plain language.",
  description:
    "The Synced changelog: dated, plain-language notes on new features and fixes in the AI inbox assistant, from new Inboxes to undo send and scheduled send.",
  eyebrow: "Company",
  intro: "User-facing changes to Synced, newest first. Most entries describe the iOS app and the service behind it.",
  answer:
    "The Synced changelog lists user-facing changes to Synced, the AI inbox assistant, grouped by week. Recent updates added SMS, GroupMe, WhatsApp Business, Instagram Business, and Messenger Inboxes, plus undo send, scheduled send, and star, snooze, and trash filters in the iOS app.",
  primaryIntent: "synced changelog release notes",
  published: "2026-09-13",
  updated: "2026-09-13",
  icon: "list",
  body: [
    { type: "h2", text: "Week of September 8, 2026" },
    { type: "h3", text: "New Inboxes" },
    {
      type: "list",
      items: [
        "[SMS](/integrations/sms) via Twilio, [GroupMe](/integrations/groupme), [WhatsApp Business](/integrations/whatsapp-business), [Instagram Business](/integrations/instagram-business), and [Messenger](/integrations/messenger) can now be connected as Inboxes.",
        "GroupMe connects through a sign-in screen instead of a pasted token.",
        "Newly connected SMS, GroupMe, and Meta Inboxes show as connected right away in the connector list.",
      ],
    },
    { type: "h3", text: "Email features in the iOS app" },
    {
      type: "list",
      items: [
        "Undo send. After you send, the message shows \"Sending…\" with an Undo countdown right in the bubble.",
        "Scheduled send. Messages you send later show a clock badge with the send time, and a red notice if sending fails. A new Scheduled filter lists them.",
        "Star, snooze, archive, and trash, with Starred, Snoozed, and Trash filters on Home. Trashed and spam conversations stay in Trash for 30 days.",
        "A Sent filter, and a Sent badge on conversations still waiting on a reply from the other side.",
        "Full email view that renders the original message, with a Hide images option and a button to open the email in Gmail or Outlook.",
        "Forward an email using the same approval sheet as replies, with To, Cc, Bcc, From, and attachments.",
        "Compose a new email from the app.",
        "Email signatures and out-of-office replies, set per account in Settings.",
        "Calendar invitations appear as cards you can respond to.",
        "Unsubscribe and report spam from a conversation.",
        "Archive and Move to Primary are now one action in the conversation menu.",
        "Newsletters and emails written in Gmail's composer display properly in the full email view.",
      ],
    },
    { type: "h3", text: "Smaller improvements" },
    {
      type: "list",
      items: [
        "Redesigned connectors screen with icons for each service.",
        "The Home filter button gives feedback when pressed.",
        "Fixed a problem where the Starred, Snoozed, and Trash views could freeze the app.",
        "Fixed an issue that could delay new Gmail messages from arriving.",
      ],
    },
    { type: "h2", text: "Week of September 1, 2026" },
    {
      type: "list",
      items: [
        "Home filters renamed to Primary, Action Needed, and Inbox.",
        "Settings shows a running total of the Action Plans Synced has written for you.",
        "A quiet \"Updating…\" label replaces the filter name while Home refreshes.",
        "A reply composer in conversations for sending a quick answer yourself.",
        "Group conversations show each sender's name and photo.",
        "The iOS app can prompt you to update when an older version is no longer supported.",
      ],
    },
    { type: "h2", text: "Week of August 25, 2026" },
    {
      type: "list",
      items: [
        "Slack group DMs and channel messages now come into Synced, including shared files and thread replies.",
        "Search on Home filters conversations by name, latest message, or platform.",
        "Pull to refresh on Home.",
        "Mark conversations read or unread from the long-press menu.",
        "Emails are labeled Primary or General, and read state is shown.",
        "A Review Needed filter for conversations with something to act on (later renamed Action Needed).",
        "Synced can edit a document it made in place when you ask for a small change, instead of rebuilding it.",
        "Synced can search the web for context when a message needs it.",
        "Fixed emails from new senders being skipped when they looked like bulk mail.",
        "More reliable file attachments, including files attached from Google Drive.",
        "Drafts you've edited in an approval sheet are kept if you leave and come back.",
      ],
    },
    { type: "h2", text: "Week of August 18, 2026" },
    {
      type: "list",
      items: [
        "Loading placeholders on Home, Tasks, Decide, Files, and Settings instead of blank screens.",
        "Fixed conversations sometimes missing their latest message, name, or avatar.",
        "The source badge on messages from Synced now reads \"Agent.\"",
      ],
    },
    { type: "h2", text: "Week of August 11, 2026" },
    {
      type: "list",
      items: [
        "Weekly [Action Plan](/glossary/action-plan) limits, with usage tracking.",
        "Voice input when answering Synced's questions, with a visual cue while it listens.",
        "A group members sheet for group conversations.",
        "Swipe to dismiss items in lists.",
        "Fixed replies you sent from Outlook with a send-as alias showing up as new incoming mail.",
      ],
    },
    { type: "h2", text: "Week of August 4, 2026" },
    {
      type: "list",
      items: [
        "The Answer screen on mobile, where Synced's approvals and questions wait for you (called [Decide](/features/decide) on the web).",
        "Attach images from your photo library.",
        "Better threading for Outlook replies.",
      ],
    },
    { type: "h2", text: "Weeks of July 21 and July 28, 2026" },
    {
      type: "list",
      items: [
        "Email approval flow: review an AI-drafted email before it is sent.",
        "Document previews, so you can see a generated file before approving it.",
        "Notification settings in your profile.",
        "Ask Synced to take on a task directly, without waiting for a message.",
        "Slack can be connected from the app with a dedicated Synced bot identity.",
        "Email filter mode setting for choosing which emails Synced treats as directed at you.",
        "Tasks now shows your full history of delegated to-dos.",
        "Fixed push notifications and how completed tasks are displayed.",
      ],
    },
    { type: "h2", text: "Weeks of July 7 and July 14, 2026" },
    {
      type: "list",
      items: [
        "[Microsoft Teams](/integrations/microsoft-teams) Inbox.",
        "[Slack](/integrations/slack) Inbox.",
        "Approval flows for Synced's work, including explicit approval before Synced changes your calendar.",
        "[OneDrive](/integrations/onedrive) support for documents.",
        "Synced can read attachments on incoming emails.",
        "Delete several generated files at once.",
        "Your own to-dos appear in the conversation timeline, with a detail view.",
        "Compact native date and time pickers for event details.",
      ],
    },
    { type: "h2", text: "Week of June 29, 2026" },
    {
      type: "list",
      items: [
        "[Outlook](/integrations/outlook) Inbox.",
        "Synced groups its work on one email thread into a single task, and can ask you several questions at once.",
        "Synced can generate documents, like slide decks, as part of an Action Plan.",
        "A note in conversations that summaries are AI-generated.",
      ],
    },
  ],
  related: ["/features", "/integrations", "/blog"],
};
